yarn/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using yarn.Models;

namespace yarn.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationUsers
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: ApplicationUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Avatar,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Avatar,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

yarn/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using yarn.Models;

namespace yarn.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Movies
        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieID,Name,Date,Rate,ReviewID,UserID,MovieURL,PosterURL")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MovieID,Name,Date,Rate,ReviewID,UserID")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

yarn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body class="py-5" style="font-family:Rubik; color:#8e8f9e">

    <!-- ------------------------------------ -->
    <!-- NAVBAR -->
    <!-- ------------------------------------ -->

    <div class="container-fluid bg-secondary fixed-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg bg-secondary navbar-dark pt-3 pb-3">

                <!-- LOGO -->

                <a class="navbar-brand mr-5" href="@Url.Action("Index", "Home" )">
                    <img class="img-fluid" alt="yarn" src="~/Images/logo0.5.svg">
                </a>

                <!-- MENU COLLAPSE (for small devices) -->

                <button class="navbar-toggler" data-toggle="collapse" data-target="#menuShrink">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="menuShrink">

                    <ul class="navbar-nav">

                        <!-- BROWSE -->

                        <li class="nav-item mr-2">
                            <a href="@Url.Action("Index", "Movies")">
                                <div class="btn btn-primary">
                                    Browse
                                </div>
                            </a>
                        </li>

                        <!-- SEARCH -->

                        <li class="nav-item">
                            <div class="input-group">
                                <input type="search" class="form-control" style="padding-right: 5rem;"
                                       placeholder="Search films or series" aria-label="search"
                                       aria-describedby="basic-addon1">
                                <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon1" style="color:#52525b">
                                        <i class="fas fa-search">
                                        </i>
                                    </span>
                                </div>
                            </div>
                        </li>

                    </ul>

                    <!-- PROFILE -->

                    @using Microsoft.AspNet.Identity
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new
                        {
                            id = "logoutForm",
                            @class =
                        "dropdown ml-auto"
                        }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="dropdown ml-auto">
                                <button type="button" class="btn btn-secondary pl-0 py-0" style="color: #8e8f9e;"
                                        id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                        data-offset="10,20">

                                    @{ 

//var currentUserId = User.Identity.GetUserId();
//var currentUserAvatar = new yarn.Models.ApplicationUser().Id

                                    }
                                    <img class="" style="width: 2.5rem;" src="~/Images/profileIcons/animal-5.svg"
                                         alt="Generic placeholder image">

                                    <i class="fas fa-caret-down pl-1"></i>
                                </button>
                                <div class="dropdown-menu bg-grey mt-2" aria-labelledby="dropdownMenuOffset">
                                    @Html.ActionLink("Profile", "Index", "Manage", routeValues: null, htmlAttributes: new {
                                   title = "Manage", @class = "dropdown-item text-grey" })
                                    @*@User.Identity.Name*@
                                    @*@{ 
                                        var currentUserId = User.Identity.GetUserId();
                                        var manager = new UserManager<currentUserId>(new UserStore<currentUserId>(new MyDbContext()));

                                            }*@
                                    
                                    
                                    <a class="dropdown-item text-grey" href="#">My Favorites</a>

                                    <!-- Admins Extra Tools -->
                                    @{ if (User.IsInRole("Admin"))
                                        {
                                            <div class="dropdown-divider"></div>
                                            <h6 class="dropdown-header" style="color: #6c719c;">Management</h6>

                                            <span class="dropdown-item text-grey">
                                                <i class="fas fa-wrench mr-2"></i>
                                                @Html.ActionLink("Manage Users", "Index", "ApplicationUsers", routeValues: null, htmlAttributes: new { title = "Manage Users", style = "color:inherit", @class = "" })
                                            </span>

                                            <span class="dropdown-item text-grey">
                                                <i class="fas fa-wrench mr-2"></i>
                                                @Html.ActionLink("Manage Movies", "Index", "Movies", routeValues: null, htmlAttributes: new { title = "Manage Movies", style = "color:inherit", @class = "" })
                                            </span>

                                        }
                                    }

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item text-grey"
                                       href="javascript:document.getElementById('logoutForm').submit()">Log off</a>

                                </div>
                            </div>
                        }
                    }

                    else
                    {
                        <ul class="nav navbar-nav ml-auto">
                            <li>
                                @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id =
                            "loginLink" })
                            </li>
                        </ul>
                    }

                </div>
            </nav>
        </div>
    </div>

    <!-- ------------------------------------ -->
    <!-- BODY -->
    <!-- ------------------------------------ -->

<div class="container-fluid bg-primary" style="margin-top: 4rem; margin-bottom: 4rem;">
    <div class="container text-primary">
        @RenderBody()
        </div>
    </div>

    <!-- ------------------------------------ -->
    <!-- FOOTER -->
    <!-- ------------------------------------ -->

    <div class="bg-secondary">
        <div class="container py-4">
            <div class="row">
                <div class="col-1 pt-2">
                    <img class="img-fluid" alt="yarn" src="~/Images/logo0.5.svg"
                         style="opacity: 0.4;">
                </div>

                <div class="col">
                    <p class="align-middle">
                        yarn is a platform for streaming content
                        <b>
                            <i>lighting-fast</i>
                        </b>
                        <br>&copy; yarn @DateTime.Now.Year
                    </p>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

yarn/Views/Shared/_LayoutAccount.cshtml
@{
    ViewBag.Title = "_LayoutAccount";
}

<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body class="m-0 p-0" style="font-family:Rubik; color:#8e8f9e">


            @RenderBody()


    <!-- ------------------------------------ -->
    <!-- FOOTER -->
    <!-- ------------------------------------ -->

    <div class="bg-secondary">
        <div class="container py-4">
            <div class="row">
                <div class="col-1 pt-2"><img class="img-fluid" alt="yarn" src="../Images/logo0.5.svg" style="opacity: 0.4;"></div>

                <div class="col">
                    <p class="align-middle">
                        yarn is a platform for streaming content
                        <b>
                            <i>lighting-fast</i>
                        </b>
                        <br>&copy; yarn
                    </p>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>