yarn-rider/Controllers/MovieController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Web.Mvc;
using yarn_rider.Models;

namespace yarn_rider.Controllers
{
    public class MovieController : Controller
    {
        SiteDbContext db = new SiteDbContext();

        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }

        [HttpGet]
        public ActionResult Index(string searchString, string searchByGenre, string searchByModifier,
            string searchByYear)
        {

            // no value to search after (display all movies)
            if (String.IsNullOrEmpty(searchString) && String.IsNullOrEmpty(searchByGenre) &&
                String.IsNullOrEmpty(searchByYear) && String.IsNullOrEmpty(searchByModifier))
            {
                return View(db.Movies.ToList());
            }

            // search for only specified value combinations (Keyword, Genre, Name, Year) 
            var movies = db.Movies.Where(m =>
                (m.Genre.ToString().Equals(searchByGenre) || String.IsNullOrEmpty(searchByGenre)) &&
                (m.MovieName.Contains(searchString) || String.IsNullOrEmpty(searchString)) &&
                (m.Date.Equals(searchByYear) || String.IsNullOrEmpty(searchByYear)));

            // search with a specified modifier (with or without combination with other values)
            switch (searchByModifier)
            {
                case "RatingAscending":
                    movies = movies.OrderBy(s => s.Rate.ToString());
                    break;

                case "RatingDescending":
                    movies = movies.OrderByDescending(s => s.Rate.ToString());
                    break;

                case "TitleAscending":
                    movies = movies.OrderBy(s => s.MovieName.ToString());
                    break;

                case "TitleDescending":
                    movies = movies.OrderByDescending(s => s.MovieName.ToString());
                    break;
            }

            return View(movies.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieID, MovieName, Date, Rate, PosterURL, MovieURL, Genre")]
            Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Movie movie = db.Movies.Find(id);
            if (movie == null) return HttpNotFound();

            ViewBag.Message = movie.MovieName;

            return View(movie);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Movie movie = db.Movies.Find(id);
            if (movie == null) return HttpNotFound();

            ViewBag.Message = movie.MovieName;

            return View(movie);
        }

        [HttpPost]
        public ActionResult Edit(Movie movie)
        {
            db.Entry(movie).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

yarn-rider/Controllers/UserController.cs
using System;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using yarn_rider.Models;

namespace yarn_rider.Controllers
{
    public class UserController : Controller
    {
        
        SiteDbContext db = new SiteDbContext();

        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            User user = db.Users.Find(id);
            if (user == null) return HttpNotFound();

            ViewBag.Message = user.UserName;

            return View(user);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //        public ActionResult Details(int? id)
        //        {
        //            if (id == null)
        //            {
        //                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //            }
        //            
        //            User user = db.Users.Find(id);
        //            if (user == null)
        //            {
        //                return HttpNotFound();
        //            }
        //            return View(user);
        //        }

    }
}

yarn-rider/Views/Shared/_Footer.cshtml
<div class="bg-secondary">
    <footer class="container py-4 ">
        <div class="row">
            <div class="col-1 pt-2">
                <img class="img-fluid" alt="yarn" src="~/Images/logo0.5.svg"
                     style="opacity: 1.0;">
            </div>
            <div class="col">
                <p class="align-middle">
                yarn is a platform for streaming content
                <b>
                    <i style="text-shadow: 1px 1px 0px #000000;color: #6d6d79;">lighting-fast</i>
                </b>
                <br>&copy; yarn @DateTime.Now.Year
                <br/><br/>

                <a href="@Url.Action("Locations", "Home")">
                    <div class="color: #6d6d79">
                        <i class="fas fa-map-marker-alt pr-1"></i>
                        Locations
                    </div>
                </a>

            </div>
        </div>
    </footer>
</div>

yarn-rider/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>yarn - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="" style="font-family:Rubik; color:#8e8f9e">

<!-- ------------------------------------ -->
<!-- NAV -->
<!-- ------------------------------------ -->

@Html.Partial("_Nav")

<!-- ------------------------------------ -->
<!-- BODY -->
<!-- ------------------------------------ -->

<div class="container-fluid bg-primary" style="margin-top: 5rem; margin-bottom: 4rem;">
    <div class="container text-primary">
        @RenderBody()
    </div>
</div>

<!-- ------------------------------------ -->
<!-- FOOTER -->
<!-- ------------------------------------ -->

@Html.Partial("_Footer")

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

yarn-rider/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>yarn - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="p-0 m-0" style="font-family:Rubik; color:#8e8f9e">


<div class="landingPage-image">
    <div class="container position-relative">
        @RenderBody()
    </div>
</div>

<!-- ------------------------------------ -->
<!-- FOOTER -->
<!-- ------------------------------------ -->

@Html.Partial("_Footer")

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

yarn-rider/Views/Shared/_LayoutMap.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>yarn - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="py-5" style="font-family:Rubik; color:#8e8f9e">

<!-- ------------------------------------ -->
<!-- NAVBAR -->
<!-- ------------------------------------ -->

@Html.Partial("_Nav")

<!-- ------------------------------------ -->
<!-- BODY -->
<!-- ------------------------------------ -->

<div class="container-fluid bg-primary m-0 p-0" style="margin-top: 4rem; margin-bottom: 4rem;">
    @RenderBody()
</div>

<!-- ------------------------------------ -->
<!-- FOOTER -->
<!-- ------------------------------------ -->

@Html.Partial("_Footer")

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

yarn-rider/Views/Shared/_Nav.cshtml
<div class="container-fluid bg-secondary fixed-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-secondary navbar-dark pt-3 pb-3">


            <!-- LOGO -->
            <a class="navbar-brand mr-5" href="@Url.Action("Index", "Home")">
                <img class="img-fluid" alt="yarn" src="~/Images/logo0.5.svg">
                @{
                    string currentUser = HttpContext.Current.User.Identity.Name;
                }
            </a>


            <!-- MENU COLLAPSE (for small devices) -->
            <button class="navbar-toggler" data-toggle="collapse" data-target="#menuShrink">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menuShrink">
                <ul class="navbar-nav">


                    <!-- BROWSE -->
                    <li class="nav-item mr-2">
                        <a href="@Url.Action("Index", "Movie")">
                            <div class="btn btn-grey">
                                Browse
                            </div>
                        </a>
                    </li>

                    <!-- SEARCH -->
                    <li class="nav-item">

                        @using (Html.BeginForm("Index", "Movie", FormMethod.Get))
                        {
                            <div class="input-group">
                                @Html.TextBox("searchString", null, new {@class = "form-control"})
                                @* <input type="submit" value="search"/> *@

                                <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon1" style="color:#52525b">
                                        <i class="fas fa-search">
                                        </i>
                                    </span>
                                </div>
                            </div>
                        }

                    </li>

                </ul>

                <!-- PROFILE -->

                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("Logout", "Account", FormMethod.Post, new
                    {
                        id = "logoutForm",
                        @class =
                            "dropdown ml-auto"
                    }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="dropdown ml-auto">

                            <button type="button" class="btn btn-secondary pl-0 py-0" style="color: #8e8f9e;"
                                    id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                    data-offset="10,20">

                                <img style="width: 2.5rem;" src="~/Images/profileIcons/0.svg"
                                     alt="Generic placeholder image">

                                <i class="fas fa-caret-down pl-1"></i>

                            </button>

                            <div class="dropdown-menu bg-grey mt-2" aria-labelledby="dropdownMenuOffset">
                                @Html.ActionLink("Profile", "Details", "User", routeValues: null, htmlAttributes: new
                                {
                                    title = "Manage", @class = "dropdown-item text-grey"
                                })

                                <a class="dropdown-item text-grey" href="#">My Favorites</a>

                                <!-- Admins Extra Tools -->
                                @{
                                    if (User.IsInRole("Admin"))
                                    {
                                        <div class="dropdown-divider"></div>
                                        <h6 class="dropdown-header" style="color: #6c719c;">Management</h6>

                                        <span class="dropdown-item text-grey">
                                            <i class="fas fa-wrench mr-2"></i>
                                            @Html.ActionLink("Manage Users", "Index", "User", routeValues: null, htmlAttributes: new {title = "Manage Users", style = "color:inherit", @class = ""})
                                        </span>

                                        <span class="dropdown-item text-grey">
                                            <i class="fas fa-wrench mr-2"></i>
                                            @Html.ActionLink("Manage Movies", "Index", "Movie", routeValues: null, htmlAttributes: new {title = "Manage Movies", style = "color:inherit", @class = ""})
                                        </span>
                                    }
                                }

                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-grey"
                                   href="javascript:document.getElementById('logoutForm').submit()">
                                    Log off
                                </a>

                            </div>
                        </div>
                    }
                }

                else
                {
                    <ul class="nav navbar-nav ml-auto">
                        <li>
                            @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new
                            {
                                id =
                                    "loginLink"
                            })
                        </li>
                    </ul>
                }


            </div>
        </nav>
    </div>
</div>

yarn-rider/Views/Shared/profile.cshtml
@model yarn_rider.Models.User